### ISSUE TITLE
Sequence Lengths filtering results?

### ISSUE THREAD

**Issue by ddofer** [philippvaeth/PROVAL#1]
In your code, for ESM-1B you keep only sequences shorter than 1022 AA long. (There is an "if" but no "else"/truncation).
https://github.com/philippvaeth/PROVAL/blob/main/proval/embedding_utils.py#L115

Do you handle it elsewhere and assert that there are no sequences longer than 1022 in all your data, used for the results in the article? Otherwise, only the ESM model would not use the longer sequences, and it's evaluation results compared to the other models (Table 3 / https://www.sciencedirect.com/science/article/pii/S2772415822000128#sec6.2) would be invalid!

**Comment by philippvaeth** [comment]
Hello, thank you very much for your comment! You are right that the sequences are filtered by length before calculating the accuracy. In our case, the ignored sequences were negligible (113/5000 sequences) and therefore the results are still representative. We also clearly stated this length limitation of the ESM-1b Transformer and removed longer sequences in the test data set as in the original paper.

Please keep in mind that we are proposing a framework for comparing embedding approaches and the reported accuracy and the selected embedding approaches are only exemplary. In practice, this should be adapted for the specific tasks and algorithms at hand!
